AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.7

#Metrics/LineLength:
#  Max: 120

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
